---
root: true
#  https://eslint.org/docs/rules/
env:
  node: true
parserOptions:
  ecmaVersion: 10
globals:
  sap: false
  SELECT: false
  INSERT: false
  UPDATE: false
  DELETE: false
  CREATE: false
  DROP: false
extends:
  - "eslint:recommended"
  - prettier
rules:
  no-unused-vars: [error]
  no-restricted-modules: [error, child_process, fs] # security
  no-eval: [error] # security
  no-implied-eval: [error] # security
  no-console: [error] # ops
  strict: [error]
  curly: [error]
